# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86140e47838600995a7a8b7d948b934c"
name = "Conative Youtube Carousel"
handle = "conative-youtube-carousel"
application_url = "https://endorsement-griffin-discovery-driven.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "citsapptesting.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://endorsement-griffin-discovery-driven.trycloudflare.com/auth/callback",
  "https://endorsement-griffin-discovery-driven.trycloudflare.com/auth/shopify/callback",
  "https://endorsement-griffin-discovery-driven.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
